### PR TITLE
ingress-nginx chart to appversion 1.10.1

### PR DESCRIPTION
**Pull request by Bdegraaf1234**
*Description of the change**

Update the ingress-nginx chart to appversion 1.10.1

**Benefits**

Security updates fixing at [least one CVE](https://github.com/kubernetes/ingress-nginx/releases?q=helm&expanded=true)

**Possible drawbacks**

None

**Applicable issues**

NA

**Additional information**

**Checklist**
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [<name_of_the_chart>])

### CODE REVIEW

**Comment by Bdegraaf1234** [comment]
@keyvaann let me know if you want to remove all the changelogs and perhaps also the CI and test folders?

**Comment by keyvaann** [comment]
Yes thanks, let's remove the those new directories. Also please keep the commands that you have used so we can add it to #65 later and make thing more automated.

**Comment by Bdegraaf1234** [comment]
this was done using the exact commands from that makefile, and removing the changelogs was:

```
rm -rf external/ingress-nginx/changelog/ external/ingress-nginx/ci/ external/ingress-nginx/tests/
```

**Comment by keyvaann** [comment]
Great. Do you know why radar-backend and kafka-manager are also involved in the new commits?

**Comment by Bdegraaf1234** [comment]
Thats was a mistake, when I run helmdocs a bunch of files get 'changed'

**Review by keyvaann — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
