### PR TITLE
[radar-upload-source-*] Fix health check and variable casting

### PR DESCRIPTION
**Pull request by blootsvoets**
**Description of the change**

- Fixes health check of backend
- Improves health check of connector to fail when no more connectors are running
- Fixes casting of long integers in deployment (prevents numbers like 2e6 instead of 2000000).

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [<name_of_the_chart>])

### CODE REVIEW

**Comment by afolarin** [comment]
To test this PR did you say we could just update the radar repository to a local folder radar-helm-charts? e.g. 

```
bases:
- ../environments.yaml

---
helmDefaults:
  atomic: true
  timeout: 120
  kubeContext: {{ .Values.kubeContext }}

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: radar
    url: https://radar-base.github.io/radar-helm-charts   ## change to ../../radar-helm-charts/
...
```

For that matter to facilitate future testing might we template that radar repository so it receives a  configurable .Value  ?

**Comment by afolarin** [comment]
Or should we add https://github.com/aslafy-z/helm-git#usage helm plugin which offers a bit of flexibility on specifying chart repos 

But if let me know if you had a different process in mind.

**Comment by afolarin** [comment]
> Or should we add https://github.com/aslafy-z/helm-git#usage helm plugin which offers a bit of flexibility on specifying chart repos
> 
> But if let me know if you had a different process in mind.

Although, testing git+https plugin -- I honestly can't get it working.

**Comment by K1Hyve** [comment]
@afolarin you should be able to use the old format to test the charts. You can close radar-helm-charts repo in RADAR-Kubernetes folder and then go to the helmfile of the certain application and change:
```
    chart: radar/radar-upload-source-connector
    version: 0.1.1
```
To:

```
    chart: ../radar-helm-charts/charts/radar-upload-source-connector
```
I haven't tested this approach yet but I assume it should be like this.

**Comment by afolarin** [comment]
> you should be able to use the old format to test the charts. You can close radar-helm-charts repo in RADAR-Kubernetes folder and then go to the helmfile of the certain application and change:

Yes, I follow that that should work, but I was hoping for a less clunky way to do this (in the event that you have a lot of charts to test) -- ok I'll give your method a go.

**Comment by afolarin** [comment]
ok I've tested above  (also updated corresponding versions numbers in `20-upload.yaml`).

changing `20-redcap.yaml` to reference the local charts for `fix-upload-connector` branch of `radar-helm-charts`
```diff
diff --git a/helmfile.d/20-upload.yaml b/helmfile.d/20-upload.yaml
index 922e82b..3ff40dc 100644
--- a/helmfile.d/20-upload.yaml
+++ b/helmfile.d/20-upload.yaml
@@ -30,8 +30,8 @@ releases:
         value: {{ .Values.radar_upload_postgres_password }}
 
   - name: radar-upload-connect-backend
-    chart: radar/radar-upload-connect-backend
-    version: 0.1.1
+    chart: ..radar-helm-charts/charts/radar-upload-connect-backend
+    version: 0.1.3
     installed: {{ .Values.radar_upload_connect_backend._install }}
     values:
       - {{ .Values.radar_upload_connect_backend | toYaml | indent 8 | trim }}
@@ -60,8 +60,8 @@ releases:
         values: [{{ .Values.server_name }}]
 
   - name: radar-upload-source-connector
-    chart: radar/radar-upload-source-connector
-    version: 0.1.1
+    chart: ../radar-helm-charts/charts/radar-upload-source-connector
+    version: 0.1.2
     installed: {{ .Values.radar_upload_source_connector._install }}
     values:
       - {{ .Values.radar_upload_source_connector | toYaml | indent 8 | trim }
```

Everything seems to be running

```sh
$ kk get pods
NAME                                                      READY   STATUS    RESTARTS   AGE
svclb-nginx-ingress-ingress-nginx-controller-v6jf2        0/2     Pending   0          9m26s
nginx-ingress-ingress-nginx-controller-68df68bc48-7r8vh   1/1     Running   0          9m26s
cp-zookeeper-0                                            2/2     Running   0          9m22s
cp-zookeeper-1                                            2/2     Running   0          8m52s
cp-zookeeper-2                                            2/2     Running   0          8m22s
cp-kafka-0                                                2/2     Running   0          7m49s
cp-kafka-1                                                2/2     Running   0          7m9s
cp-kafka-2                                                2/2     Running   0          6m29s
cp-schema-registry-5fcf566cff-6f472                       2/2     Running   0          5m45s
app-config-frontend-7b99d549f7-rcdtr                      1/1     Running   0          4m5s
postgresql-postgresql-0                                   3/3     Running   0          4m8s
timescaledb-postgresql-0                                  3/3     Running   0          4m3s
radar-grafana-56bcf6f5b4-nq4cd                            1/1     Running   0          4m1s
catalog-server-6799869c49-rdf8l                           1/1     Running   0          4m12s
app-config-7b5964657d-p8ghb                               1/1     Running   0          4m6s
radar-jdbc-connector-549dbb86b7-frt89                     1/1     Running   0          4m
management-portal-56fd7d787b-lrgbt                        1/1     Running   1          4m7s
radar-gateway-bcd998964-jblxg                             2/2     Running   0          3m59s
minio-2                                                   1/1     Running   0          2m24s
minio-3                                                   1/1     Running   0          2m24s
minio-0                                                   1/1     Running   0          2m24s
minio-1                                                   1/1     Running   0          2m24s
redis-master-0                                            2/2     Running   0          2m25s
radar-output-647ff5cfbd-f7l7m                             1/1     Running   0          118s
radar-upload-postgresql-postgresql-0                      3/3     Running   0          115s
radar-upload-connect-backend-5d8cdc6797-bgjgw             1/1     Running   0          102s
radar-upload-connect-frontend-74f5d98887-shq4g            1/1     Running   0          89s
radar-s3-connector-f8f6d7f6d-lcgcx                        1/1     Running   0          119s
radar-upload-source-connector-8d67c4687-5xrlr             1/1     Running   0          78s
```

Couple of notes:
- Naming for the ingress seems different to the instructions in #RADAR-base/RADAR-Kubernetes 
- local host accessing the applications via ingress load balancer i.e. `nginx-ingress-ingress-nginx-controller` vs `nginx-ingress-controller`
`sudo -E kubectl port-forward svc/nginx-ingress-ingress-nginx-controller 80:80 443:443`  
executes but I get a 404 on the URLs 
 `$ kubectl port-forward svc/nginx-ingress-ingress-nginx-controller 8080:80 4443:443` 
works and I can see /managementportal and /upload apps 
 not sure why the privileged port forwarding doesn't work on the 443/80

**Pull request merged**
