### PR TITLE
Update external charts via Makefile

### PR DESCRIPTION
**Pull request by keyvaann**
I've updated the Makefile to make it easier to update the dependencies.
@blootsvoets could you please tell me or update the branch with changes needed to fix the charts for our internal use?

With this changes it's now possible to update the charts individually via `make update-cert-manager` for example or all charts at once with `make deps`

### CODE REVIEW

**Comment by K1Hyve** [comment]
@blootsvoets would you be able to look into this?

**Comment by Bdegraaf1234** [comment]
@keyvaann I pushed some commits here, the script is now updated to include the new charts and works.

**Comment by keyvaann** [comment]
@Bdegraaf1234 Thanks! Please review this so we can merge it.

**Review by Bdegraaf1234 — APPROVED** [review]
LGTM

**Pull request merged**
