### PR TITLE
[radar-self-enrolment-ui] fix radar SEP ui chart

### PR DESCRIPTION
**Pull request by yatharthranjan**
**Description of the change**

Fixes a minor issue with the radar self-enrolment UI chart that prevents it from deploying.

**Benefits**

**Possible drawbacks**

**Applicable issues**

```
Error: release kratos-selfservice-ui-node failed, and has been uninstalled due to atomic being set: failed pre-install: unable to build kubernetes object for deleting hook radar-self-enrolment-ui/templates/secret.yaml: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.annotations of type string
```

**Additional information**

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [<name_of_the_chart>])

### CODE REVIEW

**Comment by mpgxvii** [comment]
Thanks for this. I was also running into an issue with the healthcheck: https://github.com/RADAR-base/radar-helm-charts/blob/0a431b92f1afc60c0d9a5cf5194e2cdc909e4da3/external/radar-self-enrolment-ui/templates/deployment.yaml#L88-L94

I've added it temporarily to the image but the endpoint is `/api/health/alive`. Or should we just remove?

**Comment by yatharthranjan** [comment]
Ok, thanks; please make an update here, in that case, to add `../api/..`. Yes, it is okay to remove it temporarily for testing purposes our production.yaml using
```
| deployment.customLivenessProbe | object | `{}` | Configure a custom livenessProbe. This overwrites the default object |
| deployment.customReadinessProbe | object | `{}` | Configure a custom readinessProbe. This overwrites the default object |
```

But please issue a fix here for the correct URL.

**Comment by keyvaann** [comment]
At the moment charts in the `external` directory are considered to be the mirror of the upstream chart and during updates they'll be removed and redownloaded from the source. If you want to make changes to it, I suggest either moving it to the `charts` directory or applying the changes in RADAR-Kubernetes repo.

**Comment by yatharthranjan** [comment]
Yes good point, @mpgxvii i think we can move this to the charts directory as it is maintained by RADAR-base and not externally.

**Comment by mpgxvii** [comment]
@keyvaann @yatharthranjan I've made the changes, but I'm not sure why the helm-docs lint check is failing. Is it because I moved it to a new directory?

**Comment by keyvaann** [comment]
@mpgxvii did you run `make gen` command?

**Comment by mpgxvii** [comment]
> @mpgxvii did you run `make gen` command?

@keyvaann Yeah but it wasn't changing anything. Apparently it was my `helm-docs` version. Updated this now.

**Review by keyvaann — APPROVED** [review]
LGTM

**Pull request merged**
