### PR TITLE
[radar-gateway] gateway

### PR DESCRIPTION
**Pull request by blootsvoets**
Bumped gateway. Used the latest version of helm-docs which apparently slightly changes the README files.

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [<name_of_the_chart>])

### CODE REVIEW

**Review by K1Hyve — CHANGES_REQUESTED** [review]
@blootsvoets please fix the linting issue

**Comment by K1Hyve** [comment]
@blootsvoets I tried to fix the chart versions but I get another linting error, I don't remember why we added the one that is failing now. Do you know about that?

**Comment by K1Hyve** [comment]
Btw the other 2 PRs should be closed before we can merge this one

**Comment by blootsvoets** [comment]
The linting issue has to do with the version of helm-docs. The latest version that will generate the correct docs is 1.8.1.

**Review by K1Hyve — APPROVED** [review]
LGTM

**Pull request merged**
