### PR TITLE
[radar-output] Cleaner interval config and sensible defaults

### PR DESCRIPTION
**Pull request by yatharthranjan**
**Description of the change**

- Makes the cleaner interval configurable
- More sensible defaults for worker interval

**Benefits**

- Reduce S3 costs by reducing the number of requests

**Possible drawbacks**

- Less frequent data extraction

**Applicable issues**

  - fixes #

**Additional information**

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [<name_of_the_chart>])

### CODE REVIEW

**Comment by blootsvoets** [comment]
Making the cleaner interval explicit is a good addition. I'm not in favour of increasing the default processing interval: it significantly increases the time until data is shown in output after it is collected. Also it increases the variability in CPU usage. Alternatively, could you explicitly document the values to be decreased to decrease S3 costs?

Other variables that may decrease costs:
1. worker cache size
2. change the output path format to `${project}/${user}/${topic}/${time:YYYYmmdd}${attempt}${extension}` to only create one file per day.
3. disable deduplication. this will reduce the number of requests and memory used by the output converter, but it may increase the storage size and will require analysts to remove duplicates at a later time.

**Comment by yatharthranjan** [comment]
Hi joris, thanks for the input.

We analysed the s3 costs in our case and most of them are due to number of requests being made to S3 particularly HEAD and LIST requests, indicating it could be due to the application scanning the whole intermediate data bucket every 90 seconds.
Making it 15 mins seems reasonable to me since this is not a near realtime use-case and kind of a historical data archive for analysis (at least that is how we are using it). IIRC this used to be 1 hour previously. Another thing to consider is the `worker.minimumFileAge` since it will not process the data until it is 900 seconds (by default) old anyways.

For your points, we are already using what is suggested in 1 and 2. 
We will try 3 as well. `deduplication.enable` is also not configurable, so will make it configurable too. 

In any case, it is fine if you think 90 seconds is better since it is configurable and we are using updated values (1 day) but thought would help someone avoid S3 costs in the future (this is fine if minio is being used). We are also in the process of setting up dashboards if the project admins need to look at data in realtime.

> Alternatively, could you explicitly document the values to be decreased to decrease S3 costs?

Yes, should that be in doc for each value that decreases the costs?

**Comment by blootsvoets** [comment]
Ok good to know. I wasn't aware that this was an issue.

> Yes, should that be in doc for each value that decreases the costs?

Or add a section in the README, like _Cost considerations_?

If you look at the radar-output code, it could perhaps be optimised to make fewer API calls, for example by
1. not rescanning the full directory hierarchy to find new topics, but limiting that to once per 15 minutes (configurable).
2. storing the actual file directories (`partition=0`, etc) to check for updates, instead of the one level above the file directory. Right now only the topic directory is stored.
3. Keeping in memory the last object that was scanned. Then do not list all files but only newly added files using [ListObjectsV2.start-after](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax). Note that you will still want to do a full scan sometimes to avoid files being skipped that were added at a later time or not deemed complete by the cleaner.

Another default that should really be changed is radar-s3-connector `flushSize`. It can be increased to at least 500 000. This makes a big difference for topics with high frequencies and reduces scanning time a lot.

**Comment by yatharthranjan** [comment]
ok thanks.

> Or add a section in the README, like Cost considerations?

ok, will add this

> If you look at the radar-output code, it could be optimised to make fewer API calls, for example by
> 1. not rescanning the full directory hierarchy to find new topics, but limiting that to once per 15 minutes (configurable).
> 2. storing the actual file directories (partition=0, etc) to check for updates, instead of the one level above the file directory. Right now only the topic directory is stored.
> 3. Keeping in memory the last object that was scanned. Then do not list all files but only newly added files using [ListObjectsV2.start-after](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax). Note that you will still want to do a full scan sometimes to avoid files being skipped that were added at a later time or not deemed complete by the cleaner.

Ok, created an issue in radar-output regarding this.

> Another default that should really be changed is radar-s3-connector flushSize. It can be increased to at least 500 000. This makes a big difference for topics with high frequencies and reduces scanning time a lot.

Yes, we have been experimenting with the flushSize. Good to know we can make it at least as high as 500 000.

**Review by blootsvoets — APPROVED** [review]
Thanks a lot @yatharthranjan, this looks very complete.

**Pull request merged**
