### PR TITLE
catalog-server to appversion 0.8.8

### PR DESCRIPTION
**Pull request by Bdegraaf1234**
**Description of the change**

Update the catalog server chart to appversion 0.8.8

**Benefits**

Security updates for the catalog server

**Possible drawbacks**

None

**Applicable issues**

NA

**Additional information**

The hotfix was applied due to an issue with accessing the confluent-cloud platform

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [<name_of_the_chart>])

### CODE REVIEW

**Review by keyvaann — COMMENTED** [review]
I suggest not having `-hotfix` in version names and keep things numerical so in future we can use automated tools for version management

**Comment by Bdegraaf1234** [comment]
So should we make another release from the same code? so that 0.8.7-hotfix==0.8.8?

**Comment by keyvaann** [comment]
> So should we make another release from the same code? so that 0.8.7-hotfix==0.8.8?

Yes indeed. We follow Semantic Versioning in radar-base
https://semver.org

**Review by keyvaann — APPROVED** [review]
LGTM

**Pull request merged**
